#                 Case Study on Testing of Hypothesis

A company started to invest in digital marketing as a new way of their product
promotions.For that they collected data and decided to carry out a study on it.

# 1. The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.

In [94]:
import pandas as pd
import numpy as np


In [55]:
data=pd.read_csv(r"C:\Users\Sadiya\Downloads\Sales_add.csv")
data.head()
data.isnull().sum()

Month                             0
Region                            0
Manager                           0
Sales_before_digital_add(in $)    0
Sales_After_digital_add(in $)     0
dtype: int64

In [56]:
from scipy.stats import ttest_rel

In [14]:
data1=ttest_rel(data["Sales_before_digital_add(in $)"],data["Sales_After_digital_add(in $)"])
data1


Ttest_relResult(statistic=-12.09070525287017, pvalue=6.336667004575778e-11)

In [58]:
t_testval=abs(data1[0])
t_testval


12.09070525287017

In [47]:
pval=data1[1]
pval


6.336667004575778e-11

In [65]:
import scipy.stats
t_val=scipy.stats.t.ppf(1-0.05,21)
print("t_val =",t_val)


t_val = 1.7207429028118775


In [66]:
if (t_testval)>=(t_val):
    print("Reject H0,there is  increase in sales afterstepping into digital marketing.")
else:
    print("Retain H0,there is no increase in sales afterstepping into digital marketing.")

Reject H0,there is  increase in sales afterstepping into digital marketing.


In [43]:
if pval<=0.05:
    print("Reject H0,there is  increase in sales afterstepping into digital marketing.")
else:
    print("Retain H0,there is no increase in sales afterstepping into digital marketing.")

Reject H0,there is  increase in sales afterstepping into digital marketing.


## Result: There is an increase in sales after stepping into digital marketing

# 2.The company needs to check whether there is any dependency between the features “Region” and “Manager”.

In [67]:
data.head()

Month      Region      Manager  Sales_before_digital_add(in $)  \
0  Month-1  Region - A  Manager - A                          132921   
1  Month-2  Region - A  Manager - C                          149559   
2  Month-3  Region - B  Manager - A                          146278   
3  Month-4  Region - B  Manager - B                          152167   
4  Month-5  Region - C  Manager - B                          159525   

   Sales_After_digital_add(in $)  
0                         270390  
1                         223334  
2                         244243  
3                         231808  
4                         258402

In [73]:
data2=pd.crosstab(data["Region"],data["Manager"])
data2

Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1

In [76]:
obs_val=data2.values
print("observed values:\n",obs_val)

observed values:
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [81]:
import scipy.stats as stats
val=stats.chi2_contingency(data2)
val

(3.050566893424036,
 0.5493991051158094,
 4,
 array([[4.09090909, 3.18181818, 2.72727273],
        [2.86363636, 2.22727273, 1.90909091],
        [2.04545455, 1.59090909, 1.36363636]]))

In [82]:
exp_val=val[3]

In [83]:
no_of_rows=len(data2.iloc[0:3,0])
no_of_colms=len(data2.iloc[0,0:3])
ddof=(no_of_rows-1)*(no_of_colms-1)
alpha=0.05
print("degrees of freedom:",ddof)

degrees of freedom: 4


In [87]:
from scipy.stats import chi2
chi_squares=sum([(o-e)**2/e for o,e in zip(obs_val,exp_val)])
chi_squares
chi_sqr_stat=chi_squares[0]+chi_squares[1]+chi_squares[2]
chi_sqr_stat
print("chi sqr statistic value:",chi_sqr_stat)

chi sqr statistic value: 3.0505668934240364


In [90]:
critical_val=chi2.ppf(q=1-0.05,df=ddof)
print("critical value:",critical_val)

critical value: 9.487729036781154


In [89]:
pvalue=1-chi2.cdf(x=chi_sqr_stat,df=ddof)
print("p value :",pvalue)

p value : 0.5493991051158094


In [93]:
if chi_sqr_stat>=critical_val:
    print("Reject H0, the features \"region\" and \"managers\" are dependent")
else:
    print("Retain H0,the features \"region\" and \"managers\" are independent")
if pvalue<=0.05:
    print("Reject H0,the features \"region\" and \"managers\" are dependent")
else:
     print("Retain H0,the features \"region\" and \"managers\" are independent")


Retain H0,the features "region" and "managers" are independent
Retain H0,the features "region" and "managers" are independent


## the features “Region” and “Manager” are independent